apiVersion: v1
kind: Namespace
metadata:
  name: ai-data
  labels:
    project: enterprise-ai-gateway
    layer: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-application
  labels:
    project: enterprise-ai-gateway
    layer: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-gateway
  labels:
    project: enterprise-ai-gateway
    layer: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-monitoring
  labels:
    project: enterprise-ai-gateway
    layer: monitoring
